[package]
name = "timetracker-cli"
version = "0.2.1"
edition.workspace = true

[dependencies]
timetracker = { path = "../timetracker" }

anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

clap = { version = "4.5.42", features = ["derive"] }
env_logger = "0.11.8"
clap_complete = "4.5.56"
textwrap = { version = "0.16", features = [] }
