[package]
name = "timetracker-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
timetracker = { path = "../timetracker" }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

clap = { version = "4.5.42", features = ["derive"] }
env_logger = "0.11.8"
